-- Genişletilmiş kelime havuzu (v2): seviye başına ~75 kelime.
-- Mevcut kelimelerle çakışma NOT EXISTS ile engellenir; tekrar çalıştırmak güvenlidir.
-- Çalıştırma:  psql "$DATABASE_URL" -f seed_words_v2.sql

-- ============ A1 (level 1) ============
INSERT INTO words (word, definition, definition_tr, ipa, part_of_speech, frequency_rank, level_id)
SELECT v.word, v.definition, v.definition_tr, v.ipa, v.pos, v.freq, v.level
FROM (VALUES
('go',        'To move from one place to another',                'gitmek',        '/ɡoʊ/',        'verb',      101, 1),
('come',      'To move toward the speaker or a place',            'gelmek',        '/kʌm/',        'verb',      102, 1),
('see',       'To notice something with your eyes',               'görmek',        '/siː/',        'verb',      103, 1),
('make',      'To create or produce something',                   'yapmak',        '/meɪk/',       'verb',      104, 1),
('take',      'To get hold of something and move it',             'almak',         '/teɪk/',       'verb',      105, 1),
('give',      'To hand something to someone',                     'vermek',        '/ɡɪv/',        'verb',      106, 1),
('know',      'To have information in your mind',                 'bilmek',        '/noʊ/',        'verb',      107, 1),
('think',     'To use your mind to form ideas',                   'düşünmek',      '/θɪŋk/',       'verb',      108, 1),
('day',       'A period of twenty four hours',                    'gün',           '/deɪ/',        'noun',      109, 1),
('night',     'The time when it is dark outside',                 'gece',          '/naɪt/',       'noun',      110, 1),
('week',      'A period of seven days',                           'hafta',         '/wiːk/',       'noun',      111, 1),
('year',      'A period of twelve months',                        'yıl',           '/jɪr/',        'noun',      112, 1),
('time',      'What is measured in minutes and hours',            'zaman',         '/taɪm/',       'noun',      113, 1),
('man',       'An adult male person',                             'adam',          '/mæn/',        'noun',      114, 1),
('woman',     'An adult female person',                           'kadın',         '/ˈwʊmən/',     'noun',      115, 1),
('child',     'A young person',                                   'çocuk',         '/tʃaɪld/',     'noun',      116, 1),
('dog',       'A common animal kept as a pet',                    'köpek',         '/dɔːɡ/',       'noun',      117, 1),
('cat',       'A small animal kept as a pet',                     'kedi',          '/kæt/',        'noun',      118, 1),
('food',      'Things that people and animals eat',               'yiyecek',       '/fuːd/',       'noun',      119, 1),
('bread',     'A basic food made from flour and baked',           'ekmek',         '/bred/',       'noun',      120, 1),
('milk',      'A white drink that comes from cows',               'süt',           '/mɪlk/',       'noun',      121, 1),
('tea',       'A hot drink made from dried leaves',               'çay',           '/tiː/',        'noun',      122, 1),
('coffee',    'A hot drink made from roasted beans',              'kahve',         '/ˈkɔːfi/',     'noun',      123, 1),
('apple',     'A round fruit with red or green skin',             'elma',          '/ˈæpəl/',      'noun',      124, 1),
('table',     'A piece of furniture with a flat top',             'masa',          '/ˈteɪbəl/',    'noun',      125, 1),
('chair',     'A piece of furniture for sitting on',              'sandalye',      '/tʃer/',       'noun',      126, 1),
('door',      'The thing you open to enter a room',               'kapı',          '/dɔːr/',       'noun',      127, 1),
('window',    'An opening in a wall with glass',                  'pencere',       '/ˈwɪndoʊ/',    'noun',      128, 1),
('room',      'A part of a building with walls',                  'oda',           '/ruːm/',       'noun',      129, 1),
('bed',       'A piece of furniture for sleeping on',             'yatak',         '/bed/',        'noun',      130, 1),
('school',    'A place where children go to learn',               'okul',          '/skuːl/',      'noun',      131, 1),
('teacher',   'A person whose job is to teach',                   'öğretmen',      '/ˈtiːtʃər/',   'noun',      132, 1),
('student',   'A person who is learning at a school',             'öğrenci',       '/ˈstuːdənt/',  'noun',      133, 1),
('car',       'A road vehicle with four wheels',                  'araba',         '/kɑːr/',       'noun',      134, 1),
('bus',       'A large road vehicle that carries people',         'otobüs',        '/bʌs/',        'noun',      135, 1),
('street',    'A road in a city or town',                         'sokak',         '/striːt/',     'noun',      136, 1),
('city',      'A large town where many people live',              'şehir',         '/ˈsɪti/',      'noun',      137, 1),
('name',      'The word that someone is called by',               'isim',          '/neɪm/',       'noun',      138, 1),
('work',      'To do a job or activity with effort',              'çalışmak',      '/wɜːrk/',      'verb',      139, 1),
('play',      'To do something for fun',                          'oynamak',       '/pleɪ/',       'verb',      140, 1),
('read',      'To look at words and understand them',             'okumak',        '/riːd/',       'verb',      141, 1),
('write',     'To put words on paper with a pen',                 'yazmak',        '/raɪt/',       'verb',      142, 1),
('listen',    'To pay attention to a sound',                      'dinlemek',      '/ˈlɪsən/',     'verb',      143, 1),
('speak',     'To say words with your voice',                     'konuşmak',      '/spiːk/',      'verb',      144, 1),
('ask',       'To say a question to someone',                     'sormak',        '/æsk/',        'verb',      145, 1),
('answer',    'To say something back to a question',              'cevaplamak',    '/ˈænsər/',     'verb',      146, 1),
('buy',       'To get something by paying money',                 'satın almak',   '/baɪ/',        'verb',      147, 1),
('money',     'What people use to buy things',                    'para',          '/ˈmʌni/',      'noun',      148, 1),
('new',       'Recently made or bought',                          'yeni',          '/nuː/',        'adjective', 149, 1),
('old',       'Having lived or existed for many years',           'eski',          '/oʊld/',       'adjective', 150, 1),
('good',      'Of high quality or pleasant',                      'iyi',           '/ɡʊd/',        'adjective', 151, 1),
('bad',       'Not good or of low quality',                       'kötü',          '/bæd/',        'adjective', 152, 1),
('hot',       'Having a high temperature',                        'sıcak',         '/hɑːt/',       'adjective', 153, 1),
('fast',      'Moving or happening quickly',                      'hızlı',         '/fæst/',       'adjective', 154, 1),
('slow',      'Not moving or happening quickly',                  'yavaş',         '/sloʊ/',       'adjective', 155, 1),
('easy',      'Not difficult to do',                              'kolay',         '/ˈiːzi/',      'adjective', 156, 1),
('long',      'Measuring a great distance or time',               'uzun',          '/lɔːŋ/',       'adjective', 157, 1),
('short',     'Measuring a small distance or time',               'kısa',          '/ʃɔːrt/',      'adjective', 158, 1),
('young',     'Having lived for only a short time',               'genç',          '/jʌŋ/',        'adjective', 159, 1),
('red',       'The color of blood',                               'kırmızı',       '/red/',        'adjective', 160, 1),
('blue',      'The color of the sky on a clear day',              'mavi',          '/bluː/',       'adjective', 161, 1),
('green',     'The color of grass',                               'yeşil',         '/ɡriːn/',      'adjective', 162, 1),
('white',     'The color of snow',                                'beyaz',         '/waɪt/',       'adjective', 163, 1),
('black',     'The darkest color',                                'siyah',         '/blæk/',       'adjective', 164, 1),
('sun',       'The star that gives us light and heat',            'güneş',         '/sʌn/',        'noun',      165, 1),
('rain',      'Water that falls from the sky',                    'yağmur',        '/reɪn/',       'noun',      166, 1),
('snow',      'Soft white pieces of frozen water',                'kar',           '/snoʊ/',       'noun',      167, 1),
('tree',      'A tall plant with a trunk and leaves',             'ağaç',          '/triː/',       'noun',      168, 1),
('flower',    'The colorful part of a plant',                     'çiçek',         '/ˈflaʊər/',    'noun',      169, 1),
('hand',      'The part of the body at the end of the arm',       'el',            '/hænd/',       'noun',      170, 1),
('head',      'The top part of the body with the face',           'baş',           '/hed/',        'noun',      171, 1),
('eye',       'The part of the body used for seeing',             'göz',           '/aɪ/',         'noun',      172, 1),
('love',      'To care about someone very much',                  'sevmek',        '/lʌv/',        'verb',      173, 1),
('want',      'To wish to have or do something',                  'istemek',       '/wɑːnt/',      'verb',      174, 1),
('sleep',     'To rest with your eyes closed at night',           'uyumak',        '/sliːp/',      'verb',      175, 1)
) AS v(word, definition, definition_tr, ipa, pos, freq, level)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE lower(w.word) = lower(v.word));

-- ============ A2 (level 2) ============
INSERT INTO words (word, definition, definition_tr, ipa, part_of_speech, frequency_rank, level_id)
SELECT v.word, v.definition, v.definition_tr, v.ipa, v.pos, v.freq, v.level
FROM (VALUES
('yesterday',  'The day before today',                                  'dün',             '/ˈjestərdeɪ/',   'adverb',    201, 2),
('tomorrow',   'The day after today',                                   'yarın',           '/təˈmɔːroʊ/',    'adverb',    202, 2),
('holiday',    'A time of rest from work or school',                    'tatil',           '/ˈhɑːlədeɪ/',    'noun',      203, 2),
('ticket',     'A piece of paper that lets you enter or travel',        'bilet',           '/ˈtɪkɪt/',       'noun',      204, 2),
('airport',    'A place where planes take off and land',                'havalimanı',      '/ˈerpɔːrt/',     'noun',      205, 2),
('station',    'A place where trains or buses stop',                    'istasyon',        '/ˈsteɪʃən/',     'noun',      206, 2),
('hotel',      'A building where you pay to stay',                      'otel',            '/hoʊˈtel/',      'noun',      207, 2),
('restaurant', 'A place where you pay to eat meals',                    'restoran',        '/ˈrestrɑːnt/',   'noun',      208, 2),
('menu',       'A list of food you can order',                          'menü',            '/ˈmenjuː/',      'noun',      209, 2),
('order',      'To ask for food or products',                           'sipariş etmek',   '/ˈɔːrdər/',      'verb',      210, 2),
('pay',        'To give money for something',                           'ödemek',          '/peɪ/',          'verb',      211, 2),
('price',      'The amount of money something costs',                   'fiyat',           '/praɪs/',        'noun',      212, 2),
('cheap',      'Costing little money',                                  'ucuz',            '/tʃiːp/',        'adjective', 213, 2),
('expensive',  'Costing a lot of money',                                'pahalı',          '/ɪkˈspensɪv/',   'adjective', 214, 2),
('borrow',     'To take something you will give back',                  'ödünç almak',     '/ˈbɔːroʊ/',      'verb',      215, 2),
('lend',       'To give something that will be returned',               'ödünç vermek',    '/lend/',         'verb',      216, 2),
('promise',    'To say you will surely do something',                   'söz vermek',      '/ˈprɑːmɪs/',     'verb',      217, 2),
('arrive',     'To reach the place you are going to',                   'varmak',          '/əˈraɪv/',       'verb',      218, 2),
('leave',      'To go away from a place',                               'ayrılmak',        '/liːv/',         'verb',      219, 2),
('return',     'To come or go back to a place',                        'geri dönmek',     '/rɪˈtɜːrn/',     'verb',      220, 2),
('stay',       'To remain in a place',                                  'kalmak',          '/steɪ/',         'verb',      221, 2),
('visit',      'To go to see a person or place',                        'ziyaret etmek',   '/ˈvɪzɪt/',       'verb',      222, 2),
('meet',       'To see and speak to someone',                           'buluşmak',        '/miːt/',         'verb',      223, 2),
('introduce',  'To tell someone another persons name',                  'tanıştırmak',     '/ˌɪntrəˈduːs/',  'verb',      224, 2),
('practice',   'To do something many times to improve',                 'pratik yapmak',   '/ˈpræktɪs/',     'verb',      225, 2),
('learn',      'To get knowledge or a new skill',                       'öğrenmek',        '/lɜːrn/',        'verb',      226, 2),
('teach',      'To help someone learn something',                       'öğretmek',        '/tiːtʃ/',        'verb',      227, 2),
('understand', 'To know the meaning of something',                      'anlamak',         '/ˌʌndərˈstænd/', 'verb',      228, 2),
('forget',     'To not remember something',                             'unutmak',         '/fərˈɡet/',      'verb',      229, 2),
('hope',       'To want something to happen',                           'ummak',           '/hoʊp/',         'verb',      230, 2),
('worry',      'To feel nervous about a problem',                       'endişelenmek',    '/ˈwɜːri/',       'verb',      231, 2),
('afraid',     'Feeling fear',                                          'korkmuş',         '/əˈfreɪd/',      'adjective', 232, 2),
('angry',      'Feeling strong displeasure',                            'kızgın',          '/ˈæŋɡri/',       'adjective', 233, 2),
('tired',      'Needing rest or sleep',                                 'yorgun',          '/ˈtaɪərd/',      'adjective', 234, 2),
('hungry',     'Wanting to eat food',                                   'aç',              '/ˈhʌŋɡri/',      'adjective', 235, 2),
('thirsty',    'Wanting to drink something',                            'susamış',         '/ˈθɜːrsti/',     'adjective', 236, 2),
('bored',      'Feeling tired because nothing is interesting',          'sıkılmış',        '/bɔːrd/',        'adjective', 237, 2),
('excited',    'Feeling very happy about something',                    'heyecanlı',       '/ɪkˈsaɪtɪd/',    'adjective', 238, 2),
('surprised',  'Feeling wonder at something unexpected',                'şaşırmış',        '/sərˈpraɪzd/',   'adjective', 239, 2),
('interested', 'Wanting to know more about something',                  'ilgili',          '/ˈɪntrəstɪd/',   'adjective', 240, 2),
('famous',     'Known by many people',                                  'ünlü',            '/ˈfeɪməs/',      'adjective', 241, 2),
('popular',    'Liked by many people',                                  'popüler',         '/ˈpɑːpjələr/',   'adjective', 242, 2),
('important',  'Having great value or meaning',                         'önemli',          '/ɪmˈpɔːrtənt/',  'adjective', 243, 2),
('different',  'Not the same as another',                               'farklı',          '/ˈdɪfrənt/',     'adjective', 244, 2),
('similar',    'Almost the same as another',                            'benzer',          '/ˈsɪmələr/',     'adjective', 245, 2),
('quiet',      'Making little or no noise',                             'sessiz',          '/ˈkwaɪət/',      'adjective', 246, 2),
('noisy',      'Making a lot of sound',                                 'gürültülü',       '/ˈnɔɪzi/',       'adjective', 247, 2),
('crowded',    'Full of people',                                        'kalabalık',       '/ˈkraʊdɪd/',     'adjective', 248, 2),
('empty',      'Containing nothing',                                    'boş',             '/ˈempti/',       'adjective', 249, 2),
('full',       'Containing as much as possible',                        'dolu',            '/fʊl/',          'adjective', 250, 2),
('heavy',      'Weighing a lot',                                        'ağır',            '/ˈhevi/',        'adjective', 251, 2),
('light',      'Weighing little',                                       'hafif',           '/laɪt/',         'adjective', 252, 2),
('strong',     'Having a lot of physical power',                        'güçlü',           '/strɔːŋ/',       'adjective', 253, 2),
('weak',       'Not having much power or strength',                     'zayıf',           '/wiːk/',         'adjective', 254, 2),
('early',      'Before the usual or expected time',                     'erken',           '/ˈɜːrli/',       'adverb',    255, 2),
('late',       'After the usual or expected time',                      'geç',             '/leɪt/',         'adverb',    256, 2),
('often',      'Many times',                                            'sık sık',         '/ˈɔːfən/',       'adverb',    257, 2),
('sometimes',  'On some occasions but not always',                      'bazen',           '/ˈsʌmtaɪmz/',    'adverb',    258, 2),
('usually',    'In the way that most often happens',                    'genellikle',      '/ˈjuːʒuəli/',    'adverb',    259, 2),
('always',     'At all times',                                          'her zaman',       '/ˈɔːlweɪz/',     'adverb',    260, 2),
('never',      'Not at any time',                                       'asla',            '/ˈnevər/',       'adverb',    261, 2),
('weekend',    'Saturday and Sunday',                                   'hafta sonu',      '/ˈwiːkend/',     'noun',      262, 2),
('neighbor',   'A person who lives near you',                           'komşu',           '/ˈneɪbər/',      'noun',      263, 2),
('guest',      'A person you invite to your home',                      'misafir',         '/ɡest/',         'noun',      264, 2),
('message',    'Written or spoken information you send',                'mesaj',           '/ˈmesɪdʒ/',      'noun',      265, 2),
('letter',     'A written message sent by post',                        'mektup',          '/ˈletər/',       'noun',      266, 2),
('news',       'Information about recent events',                       'haber',           '/nuːz/',         'noun',      267, 2),
('question',   'A sentence that asks for information',                  'soru',            '/ˈkwestʃən/',    'noun',      268, 2),
('problem',    'Something difficult that needs a solution',             'sorun',           '/ˈprɑːbləm/',    'noun',      269, 2),
('reply',      'To answer someone in speech or writing',                'yanıtlamak',      '/rɪˈplaɪ/',      'verb',      270, 2),
('finish',     'To complete something',                                 'bitirmek',        '/ˈfɪnɪʃ/',       'verb',      271, 2),
('begin',      'To start something',                                    'başlamak',        '/bɪˈɡɪn/',       'verb',      272, 2),
('carry',      'To hold something and take it somewhere',               'taşımak',         '/ˈkæri/',        'verb',      273, 2),
('send',       'To make something go to another place',                 'göndermek',       '/send/',         'verb',      274, 2),
('receive',    'To get something that is sent to you',                  'almak',           '/rɪˈsiːv/',      'verb',      275, 2)
) AS v(word, definition, definition_tr, ipa, pos, freq, level)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE lower(w.word) = lower(v.word));

-- ============ B1 (level 3) ============
INSERT INTO words (word, definition, definition_tr, ipa, part_of_speech, frequency_rank, level_id)
SELECT v.word, v.definition, v.definition_tr, v.ipa, v.pos, v.freq, v.level
FROM (VALUES
('accomplish',  'To finish something successfully',                       'başarmak',           '/əˈkɑːmplɪʃ/',   'verb',      301, 3),
('admire',      'To respect and like someone or something',               'hayran olmak',       '/ədˈmaɪər/',     'verb',      302, 3),
('adjust',      'To change something slightly to make it fit',            'ayarlamak',          '/əˈdʒʌst/',      'verb',      303, 3),
('advise',      'To tell someone what you think they should do',          'tavsiye etmek',      '/ədˈvaɪz/',      'verb',      304, 3),
('afford',      'To have enough money to buy something',                  'gücü yetmek',        '/əˈfɔːrd/',      'verb',      305, 3),
('agree',       'To have the same opinion as someone',                    'katılmak',           '/əˈɡriː/',       'verb',      306, 3),
('allow',       'To give permission for something',                       'izin vermek',        '/əˈlaʊ/',        'verb',      307, 3),
('announce',    'To tell people about something officially',              'duyurmak',           '/əˈnaʊns/',      'verb',      308, 3),
('apologize',   'To say you are sorry',                                   'özür dilemek',       '/əˈpɑːlədʒaɪz/', 'verb',      309, 3),
('appear',      'To start to be seen',                                    'görünmek',           '/əˈpɪr/',        'verb',      310, 3),
('apply',       'To make a formal request for something',                 'başvurmak',          '/əˈplaɪ/',       'verb',      311, 3),
('appointment', 'An arrangement to meet at a set time',                   'randevu',            '/əˈpɔɪntmənt/',  'noun',      312, 3),
('argue',       'To speak angrily because you disagree',                  'tartışmak',          '/ˈɑːrɡjuː/',     'verb',      313, 3),
('arrange',     'To plan or organize something',                          'düzenlemek',         '/əˈreɪndʒ/',     'verb',      314, 3),
('attend',      'To go to an event or place',                             'katılmak',           '/əˈtend/',       'verb',      315, 3),
('avoid',       'To stay away from something',                            'kaçınmak',           '/əˈvɔɪd/',       'verb',      316, 3),
('aware',       'Knowing that something exists',                          'farkında',           '/əˈwer/',        'adjective', 317, 3),
('behave',      'To act in a particular way',                             'davranmak',          '/bɪˈheɪv/',      'verb',      318, 3),
('belong',      'To be the property of someone',                          'ait olmak',          '/bɪˈlɔːŋ/',      'verb',      319, 3),
('benefit',     'A helpful or good effect',                               'fayda',              '/ˈbenɪfɪt/',     'noun',      320, 3),
('calculate',   'To find an amount using mathematics',                    'hesaplamak',         '/ˈkælkjəleɪt/',  'verb',      321, 3),
('cancel',      'To decide that a planned event will not happen',         'iptal etmek',        '/ˈkænsəl/',      'verb',      322, 3),
('celebrate',   'To do something enjoyable for a special day',            'kutlamak',           '/ˈselɪbreɪt/',   'verb',      323, 3),
('challenge',   'Something difficult that tests your ability',            'zorluk',             '/ˈtʃælɪndʒ/',    'noun',      324, 3),
('community',   'A group of people living in the same area',              'topluluk',           '/kəˈmjuːnəti/',  'noun',      325, 3),
('compare',     'To look at differences between things',                  'karşılaştırmak',     '/kəmˈper/',      'verb',      326, 3),
('complain',    'To say you are not satisfied',                           'şikayet etmek',      '/kəmˈpleɪn/',    'verb',      327, 3),
('complete',    'To finish doing or making something',                    'tamamlamak',         '/kəmˈpliːt/',    'verb',      328, 3),
('confident',   'Sure of your own abilities',                             'kendinden emin',     '/ˈkɑːnfɪdənt/',  'adjective', 329, 3),
('confirm',     'To say that something is definitely true',               'onaylamak',          '/kənˈfɜːrm/',    'verb',      330, 3),
('connect',     'To join two things together',                            'bağlamak',           '/kəˈnekt/',      'verb',      331, 3),
('continue',    'To keep doing something',                                'devam etmek',        '/kənˈtɪnjuː/',   'verb',      332, 3),
('convince',    'To make someone believe something',                      'ikna etmek',         '/kənˈvɪns/',     'verb',      333, 3),
('culture',     'The customs and beliefs of a group',                     'kültür',             '/ˈkʌltʃər/',     'noun',      334, 3),
('curious',     'Wanting to know or learn about things',                  'meraklı',            '/ˈkjʊriəs/',     'adjective', 335, 3),
('damage',      'Physical harm to something',                             'hasar',              '/ˈdæmɪdʒ/',      'noun',      336, 3),
('deliver',     'To take something to a person or place',                 'teslim etmek',       '/dɪˈlɪvər/',     'verb',      337, 3),
('deny',        'To say that something is not true',                      'inkar etmek',        '/dɪˈnaɪ/',       'verb',      338, 3),
('depend',      'To need someone or something',                           'bağlı olmak',        '/dɪˈpend/',      'verb',      339, 3),
('describe',    'To say what something is like',                          'tanımlamak',         '/dɪˈskraɪb/',    'verb',      340, 3),
('deserve',     'To be worthy of something',                              'hak etmek',          '/dɪˈzɜːrv/',     'verb',      341, 3),
('develop',     'To grow or make something grow',                         'geliştirmek',        '/dɪˈveləp/',     'verb',      342, 3),
('disappear',   'To stop being visible',                                  'kaybolmak',          '/ˌdɪsəˈpɪr/',    'verb',      343, 3),
('discover',    'To find something for the first time',                   'keşfetmek',          '/dɪˈskʌvər/',    'verb',      344, 3),
('discuss',     'To talk about something with others',                    'tartışmak',          '/dɪˈskʌs/',      'verb',      345, 3),
('effort',      'Physical or mental energy used to do something',         'çaba',               '/ˈefərt/',       'noun',      346, 3),
('environment', 'The natural world around us',                            'çevre',              '/ɪnˈvaɪrənmənt/','noun',      347, 3),
('essential',   'Completely necessary',                                   'gerekli',            '/ɪˈsenʃəl/',     'adjective', 348, 3),
('examine',     'To look at something carefully',                         'incelemek',          '/ɪɡˈzæmɪn/',     'verb',      349, 3),
('expect',      'To think that something will happen',                    'beklemek',           '/ɪkˈspekt/',     'verb',      350, 3),
('experience',  'Knowledge you get from doing things',                    'deneyim',            '/ɪkˈspɪriəns/',  'noun',      351, 3),
('familiar',    'Well known to you',                                      'tanıdık',            '/fəˈmɪliər/',    'adjective', 352, 3),
('generous',    'Willing to give money or help freely',                   'cömert',             '/ˈdʒenərəs/',    'adjective', 353, 3),
('government',  'The group of people who control a country',              'hükümet',            '/ˈɡʌvərnmənt/',  'noun',      354, 3),
('guess',       'To give an answer without being sure',                   'tahmin etmek',       '/ɡes/',          'verb',      355, 3),
('habit',       'Something you do regularly',                             'alışkanlık',         '/ˈhæbɪt/',       'noun',      356, 3),
('identify',    'To recognize what something is',                         'tanımlamak',         '/aɪˈdentɪfaɪ/',  'verb',      357, 3),
('imagine',     'To form a picture in your mind',                         'hayal etmek',        '/ɪˈmædʒɪn/',     'verb',      358, 3),
('include',     'To have something as a part',                            'içermek',            '/ɪnˈkluːd/',     'verb',      359, 3),
('increase',    'To become larger in amount',                             'artmak',             '/ɪnˈkriːs/',     'verb',      360, 3),
('influence',   'The power to change how someone thinks',                 'etki',               '/ˈɪnfluəns/',    'noun',      361, 3),
('inform',      'To give information to someone',                         'bilgilendirmek',     '/ɪnˈfɔːrm/',     'verb',      362, 3),
('intend',      'To plan to do something',                                'niyet etmek',        '/ɪnˈtend/',      'verb',      363, 3),
('involve',     'To include as a necessary part',                         'içermek',            '/ɪnˈvɑːlv/',     'verb',      364, 3),
('manage',      'To succeed in doing something difficult',                'başarmak',           '/ˈmænɪdʒ/',      'verb',      365, 3),
('measure',     'To find the size or amount of something',                'ölçmek',             '/ˈmeʒər/',       'verb',      366, 3),
('mention',     'To speak about something briefly',                       'bahsetmek',          '/ˈmenʃən/',      'verb',      367, 3),
('necessary',   'Needed in order to do something',                        'gerekli',            '/ˈnesəseri/',    'adjective', 368, 3),
('obvious',     'Easy to see or understand',                              'açık',               '/ˈɑːbviəs/',     'adjective', 369, 3),
('offer',       'To say you will give or do something',                   'teklif etmek',       '/ˈɔːfər/',       'verb',      370, 3),
('opportunity', 'A chance to do something good',                          'fırsat',             '/ˌɑːpərˈtuːnəti/','noun',     371, 3),
('organize',    'To plan and arrange something',                          'organize etmek',     '/ˈɔːrɡənaɪz/',   'verb',      372, 3),
('prefer',      'To like one thing more than another',                    'tercih etmek',       '/prɪˈfɜːr/',     'verb',      373, 3),
('prevent',     'To stop something from happening',                       'önlemek',            '/prɪˈvent/',     'verb',      374, 3),
('provide',     'To give something that is needed',                       'sağlamak',           '/prəˈvaɪd/',     'verb',      375, 3)
) AS v(word, definition, definition_tr, ipa, pos, freq, level)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE lower(w.word) = lower(v.word));

-- ============ B2 (level 4) ============
INSERT INTO words (word, definition, definition_tr, ipa, part_of_speech, frequency_rank, level_id)
SELECT v.word, v.definition, v.definition_tr, v.ipa, v.pos, v.freq, v.level
FROM (VALUES
('abundant',     'Existing in large quantities',                            'bol',                 '/əˈbʌndənt/',     'adjective', 401, 4),
('accommodate',  'To provide space or a room for someone',                  'barındırmak',         '/əˈkɑːmədeɪt/',   'verb',      402, 4),
('accumulate',   'To gradually collect more and more',                      'biriktirmek',         '/əˈkjuːmjəleɪt/', 'verb',      403, 4),
('acknowledge',  'To accept that something is true',                        'kabul etmek',         '/əkˈnɑːlɪdʒ/',    'verb',      404, 4),
('acquire',      'To get or gain something',                                'edinmek',             '/əˈkwaɪər/',      'verb',      405, 4),
('adequate',     'Enough for a particular purpose',                         'yeterli',             '/ˈædɪkwət/',      'adjective', 406, 4),
('allocate',     'To officially give something for a purpose',              'tahsis etmek',        '/ˈæləkeɪt/',      'verb',      407, 4),
('ambition',     'A strong desire to achieve something',                    'hırs',                '/æmˈbɪʃən/',      'noun',      408, 4),
('apparent',     'Easy to see or understand',                               'aşikar',              '/əˈpærənt/',      'adjective', 409, 4),
('appreciate',   'To recognize the value of something',                     'takdir etmek',        '/əˈpriːʃieɪt/',   'verb',      410, 4),
('arbitrary',    'Based on chance rather than reason',                      'keyfi',               '/ˈɑːrbɪtreri/',   'adjective', 411, 4),
('assess',       'To judge the quality or value of something',              'değerlendirmek',      '/əˈses/',         'verb',      412, 4),
('assume',       'To believe something without proof',                      'varsaymak',           '/əˈsuːm/',        'verb',      413, 4),
('attain',       'To reach a goal after much effort',                       'ulaşmak',             '/əˈteɪn/',        'verb',      414, 4),
('attribute',    'To say something is caused by something else',            'atfetmek',            '/əˈtrɪbjuːt/',    'verb',      415, 4),
('authentic',    'Real and not a copy',                                     'özgün',               '/ɔːˈθentɪk/',     'adjective', 416, 4),
('bias',         'An unfair preference for one side',                       'önyargı',             '/ˈbaɪəs/',        'noun',      417, 4),
('boost',        'To increase or improve something',                        'artırmak',            '/buːst/',         'verb',      418, 4),
('capacity',     'The amount something can hold or produce',                'kapasite',            '/kəˈpæsəti/',     'noun',      419, 4),
('cease',        'To stop happening or doing something',                    'sona ermek',          '/siːs/',          'verb',      420, 4),
('circumstance', 'A condition that affects a situation',                    'koşul',               '/ˈsɜːrkəmstæns/', 'noun',      421, 4),
('clarify',      'To make something easier to understand',                  'açıklığa kavuşturmak','/ˈklærɪfaɪ/',     'verb',      422, 4),
('coincide',     'To happen at the same time',                              'denk gelmek',         '/ˌkoʊɪnˈsaɪd/',   'verb',      423, 4),
('collaborate',  'To work together on a project',                           'iş birliği yapmak',   '/kəˈlæbəreɪt/',   'verb',      424, 4),
('commitment',   'A promise to do something',                               'taahhüt',             '/kəˈmɪtmənt/',    'noun',      425, 4),
('compel',       'To force someone to do something',                        'zorlamak',            '/kəmˈpel/',       'verb',      426, 4),
('compensate',   'To pay someone for loss or damage',                       'telafi etmek',        '/ˈkɑːmpənseɪt/',  'verb',      427, 4),
('competent',    'Having the skill to do something well',                   'yetkin',              '/ˈkɑːmpɪtənt/',   'adjective', 428, 4),
('comprise',     'To consist of particular parts',                          'oluşmak',             '/kəmˈpraɪz/',     'verb',      429, 4),
('conceal',      'To hide something carefully',                             'gizlemek',            '/kənˈsiːl/',      'verb',      430, 4),
('concede',      'To admit something is true unwillingly',                  'kabullenmek',         '/kənˈsiːd/',      'verb',      431, 4),
('conceive',     'To imagine or think of an idea',                          'tasarlamak',          '/kənˈsiːv/',      'verb',      432, 4),
('condemn',      'To criticize something strongly',                         'kınamak',             '/kənˈdem/',       'verb',      433, 4),
('confine',      'To keep within limits',                                   'sınırlamak',          '/kənˈfaɪn/',      'verb',      434, 4),
('conform',      'To behave according to rules or customs',                 'uymak',               '/kənˈfɔːrm/',     'verb',      435, 4),
('confront',     'To face a difficult situation directly',                  'yüzleşmek',           '/kənˈfrʌnt/',     'verb',      436, 4),
('consensus',    'General agreement among a group',                         'fikir birliği',       '/kənˈsensəs/',    'noun',      437, 4),
('consequence',  'A result of an action',                                   'sonuç',               '/ˈkɑːnsɪkwens/',  'noun',      438, 4),
('considerable', 'Large in amount or degree',                               'önemli ölçüde',       '/kənˈsɪdərəbəl/', 'adjective', 439, 4),
('consistent',   'Always behaving in the same way',                         'tutarlı',             '/kənˈsɪstənt/',   'adjective', 440, 4),
('constitute',   'To form or make up something',                            'oluşturmak',          '/ˈkɑːnstɪtuːt/',  'verb',      441, 4),
('constrain',    'To limit or restrict something',                          'kısıtlamak',          '/kənˈstreɪn/',    'verb',      442, 4),
('contemplate',  'To think about something deeply',                         'derin düşünmek',      '/ˈkɑːntəmpleɪt/', 'verb',      443, 4),
('contradict',   'To say the opposite of what was said',                    'çelişmek',            '/ˌkɑːntrəˈdɪkt/', 'verb',      444, 4),
('controversy',  'Strong public disagreement',                              'tartışma',            '/ˈkɑːntrəvɜːrsi/','noun',      445, 4),
('convey',       'To communicate a message or feeling',                     'iletmek',             '/kənˈveɪ/',       'verb',      446, 4),
('cope',         'To deal successfully with a problem',                     'başa çıkmak',         '/koʊp/',          'verb',      447, 4),
('credible',     'Able to be believed or trusted',                          'inandırıcı',          '/ˈkredəbəl/',     'adjective', 448, 4),
('crucial',      'Extremely important',                                     'çok önemli',          '/ˈkruːʃəl/',      'adjective', 449, 4),
('cultivate',    'To develop a skill or quality',                           'geliştirmek',         '/ˈkʌltɪveɪt/',    'verb',      450, 4),
('decline',      'To become smaller or weaker',                             'azalmak',             '/dɪˈklaɪn/',      'verb',      451, 4),
('dedicate',     'To give time and energy to something',                    'adamak',              '/ˈdedɪkeɪt/',     'verb',      452, 4),
('deduce',       'To reach an answer by reasoning',                         'çıkarım yapmak',      '/dɪˈduːs/',       'verb',      453, 4),
('demonstrate',  'To show clearly that something is true',                  'göstermek',           '/ˈdemənstreɪt/',  'verb',      454, 4),
('deprive',      'To take something necessary away',                        'mahrum bırakmak',     '/dɪˈpraɪv/',      'verb',      455, 4),
('derive',       'To get something from a source',                          'türetmek',            '/dɪˈraɪv/',       'verb',      456, 4),
('designate',    'To choose someone for a particular job',                  'atamak',              '/ˈdezɪɡneɪt/',    'verb',      457, 4),
('deteriorate',  'To become worse over time',                               'kötüleşmek',          '/dɪˈtɪriəreɪt/',  'verb',      458, 4),
('devote',       'To give all your time to something',                      'adamak',              '/dɪˈvoʊt/',       'verb',      459, 4),
('dilemma',      'A difficult choice between two options',                  'ikilem',              '/dɪˈlemə/',       'noun',      460, 4),
('disclose',     'To make secret information known',                        'ifşa etmek',          '/dɪsˈkloʊz/',     'verb',      461, 4),
('dispute',      'A disagreement or argument',                              'anlaşmazlık',         '/dɪˈspjuːt/',     'noun',      462, 4),
('distinct',     'Clearly different or separate',                           'belirgin',            '/dɪˈstɪŋkt/',     'adjective', 463, 4),
('distort',      'To change something so it is no longer true',             'çarpıtmak',           '/dɪˈstɔːrt/',     'verb',      464, 4),
('distribute',   'To give things out to many people',                       'dağıtmak',            '/dɪˈstrɪbjuːt/',  'verb',      465, 4),
('diverse',      'Including many different types',                          'çeşitli',             '/daɪˈvɜːrs/',     'adjective', 466, 4),
('dominate',     'To have control or power over something',                 'hükmetmek',           '/ˈdɑːmɪneɪt/',    'verb',      467, 4),
('drastic',      'Extreme and sudden',                                      'sert',                '/ˈdræstɪk/',      'adjective', 468, 4),
('elicit',       'To get a response or reaction from someone',              'ortaya çıkarmak',     '/ɪˈlɪsɪt/',       'verb',      469, 4),
('embrace',      'To accept an idea willingly',                             'benimsemek',          '/ɪmˈbreɪs/',      'verb',      470, 4),
('emerge',       'To appear or become known',                               'ortaya çıkmak',       '/ɪˈmɜːrdʒ/',      'verb',      471, 4),
('emphasize',    'To give special importance to something',                 'vurgulamak',          '/ˈemfəsaɪz/',     'verb',      472, 4),
('endeavor',     'A serious attempt to do something',                       'çaba',                '/ɪnˈdevər/',      'noun',      473, 4),
('enhance',      'To improve the quality of something',                     'iyileştirmek',        '/ɪnˈhæns/',       'verb',      474, 4),
('exploit',      'To use something fully for advantage',                    'yararlanmak',         '/ɪkˈsplɔɪt/',     'verb',      475, 4)
) AS v(word, definition, definition_tr, ipa, pos, freq, level)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE lower(w.word) = lower(v.word));

-- ============ C1 (level 5) ============
INSERT INTO words (word, definition, definition_tr, ipa, part_of_speech, frequency_rank, level_id)
SELECT v.word, v.definition, v.definition_tr, v.ipa, v.pos, v.freq, v.level
FROM (VALUES
('abstain',      'To choose not to do something',                          'kaçınmak',            '/əbˈsteɪn/',      'verb',      501, 5),
('acquiesce',    'To accept something without protest',                    'razı olmak',          '/ˌækwiˈes/',      'verb',      502, 5),
('adroit',       'Skillful and clever',                                    'becerikli',           '/əˈdrɔɪt/',       'adjective', 503, 5),
('aesthetic',    'Relating to beauty and art',                             'estetik',             '/esˈθetɪk/',      'adjective', 504, 5),
('affluent',     'Having a lot of money',                                  'varlıklı',            '/ˈæfluənt/',      'adjective', 505, 5),
('aggravate',    'To make a bad situation worse',                          'kötüleştirmek',       '/ˈæɡrəveɪt/',     'verb',      506, 5),
('allude',       'To mention something indirectly',                        'ima etmek',           '/əˈluːd/',        'verb',      507, 5),
('aloof',        'Distant and not friendly',                               'mesafeli',            '/əˈluːf/',        'adjective', 508, 5),
('altruistic',   'Caring about others more than yourself',                 'özgecil',             '/ˌæltruˈɪstɪk/',  'adjective', 509, 5),
('ambivalent',   'Having mixed feelings about something',                  'kararsız',            '/æmˈbɪvələnt/',   'adjective', 510, 5),
('ameliorate',   'To make something better',                               'iyileştirmek',        '/əˈmiːliəreɪt/',  'verb',      511, 5),
('analogous',    'Similar in some ways',                                   'benzer',              '/əˈnæləɡəs/',     'adjective', 512, 5),
('animosity',    'Strong dislike or hatred',                               'düşmanlık',           '/ˌænɪˈmɑːsəti/',  'noun',      513, 5),
('anomaly',      'Something different from what is normal',                'anomali',             '/əˈnɑːməli/',     'noun',      514, 5),
('apathy',       'Lack of interest or emotion',                            'kayıtsızlık',         '/ˈæpəθi/',        'noun',      515, 5),
('appease',      'To calm someone by giving what they want',               'yatıştırmak',         '/əˈpiːz/',        'verb',      516, 5),
('apprehensive', 'Worried about something that may happen',                'endişeli',            '/ˌæprɪˈhensɪv/',  'adjective', 517, 5),
('arduous',      'Requiring a lot of effort',                              'zahmetli',            '/ˈɑːrdʒuəs/',     'adjective', 518, 5),
('ascertain',    'To find out something for certain',                      'saptamak',            '/ˌæsərˈteɪn/',    'verb',      519, 5),
('aspire',       'To have a strong desire to achieve',                     'arzulamak',           '/əˈspaɪər/',      'verb',      520, 5),
('astute',       'Clever and quick to understand',                         'zeki',                '/əˈstuːt/',       'adjective', 521, 5),
('audacious',    'Willing to take bold risks',                             'cüretkar',            '/ɔːˈdeɪʃəs/',     'adjective', 522, 5),
('augment',      'To increase in size or amount',                          'artırmak',            '/ɔːɡˈment/',      'verb',      523, 5),
('austere',      'Very plain and simple, without comfort',                 'sade',                '/ɔːˈstɪr/',       'adjective', 524, 5),
('autonomous',   'Independent and self-governing',                         'özerk',               '/ɔːˈtɑːnəməs/',   'adjective', 525, 5),
('avert',        'To prevent something bad from happening',                'önlemek',             '/əˈvɜːrt/',       'verb',      526, 5),
('benevolent',   'Kind and wanting to help others',                        'hayırsever',          '/bəˈnevələnt/',   'adjective', 527, 5),
('blatant',      'Done openly without shame',                              'bariz',               '/ˈbleɪtənt/',     'adjective', 528, 5),
('bolster',      'To support or strengthen something',                     'desteklemek',         '/ˈboʊlstər/',     'verb',      529, 5),
('brevity',      'The quality of being short in speech',                   'kısalık',             '/ˈbrevəti/',      'noun',      530, 5),
('candor',       'Honest and open speech',                                 'açık sözlülük',       '/ˈkændər/',       'noun',      531, 5),
('capricious',   'Changing mood or behavior suddenly',                     'kaprisli',            '/kəˈprɪʃəs/',     'adjective', 532, 5),
('censure',      'Strong official criticism',                              'kınama',              '/ˈsenʃər/',       'noun',      533, 5),
('coerce',       'To force someone by using threats',                      'zorlamak',            '/koʊˈɜːrs/',      'verb',      534, 5),
('cogent',       'Clear, logical, and convincing',                         'ikna edici',          '/ˈkoʊdʒənt/',     'adjective', 535, 5),
('complacent',   'Too satisfied and unaware of danger',                    'rehavete kapılmış',   '/kəmˈpleɪsənt/',  'adjective', 536, 5),
('concise',      'Giving information clearly in few words',                'özlü',                '/kənˈsaɪs/',      'adjective', 537, 5),
('concur',       'To agree with someone',                                  'hemfikir olmak',      '/kənˈkɜːr/',      'verb',      538, 5),
('condone',      'To accept behavior that is wrong',                       'göz yummak',          '/kənˈdoʊn/',      'verb',      539, 5),
('conscientious','Careful and thorough in work',                           'vicdanlı',            '/ˌkɑːnʃiˈenʃəs/', 'adjective', 540, 5),
('consolidate',  'To combine things into one stronger whole',              'pekiştirmek',         '/kənˈsɑːlɪdeɪt/', 'verb',      541, 5),
('conspicuous',  'Very easy to notice',                                    'göze çarpan',         '/kənˈspɪkjuəs/',  'adjective', 542, 5),
('contempt',     'A feeling that something deserves no respect',           'küçümseme',           '/kənˈtempt/',     'noun',      543, 5),
('contend',      'To claim or argue that something is true',               'iddia etmek',         '/kənˈtend/',      'verb',      544, 5),
('contentious',  'Likely to cause argument',                               'tartışmalı',          '/kənˈtenʃəs/',    'adjective', 545, 5),
('converge',     'To come together at one point',                          'birleşmek',           '/kənˈvɜːrdʒ/',    'verb',      546, 5),
('conviction',   'A strong belief or opinion',                             'inanç',               '/kənˈvɪkʃən/',    'noun',      547, 5),
('copious',      'In large amounts',                                       'bol miktarda',        '/ˈkoʊpiəs/',      'adjective', 548, 5),
('corroborate',  'To confirm with additional evidence',                    'doğrulamak',          '/kəˈrɑːbəreɪt/',  'verb',      549, 5),
('covert',       'Secret or hidden',                                       'gizli',               '/ˈkoʊvɜːrt/',     'adjective', 550, 5),
('culminate',    'To reach the highest or final point',                    'sonuçlanmak',         '/ˈkʌlmɪneɪt/',    'verb',      551, 5),
('cumbersome',   'Difficult to use because of size or weight',             'hantal',              '/ˈkʌmbərsəm/',    'adjective', 552, 5),
('curtail',      'To reduce or limit something',                           'kısıtlamak',          '/kɜːrˈteɪl/',     'verb',      553, 5),
('daunting',     'Making you feel worried about difficulty',               'göz korkutucu',       '/ˈdɔːntɪŋ/',      'adjective', 554, 5),
('dearth',       'A lack of something',                                    'kıtlık',              '/dɜːrθ/',         'noun',      555, 5),
('deference',    'Polite respect for someone',                             'saygı',               '/ˈdefərəns/',     'noun',      556, 5),
('deft',         'Skillful and quick with hands or mind',                  'usta',                '/deft/',          'adjective', 557, 5),
('delineate',    'To describe something precisely',                        'tanımlamak',          '/dɪˈlɪnieɪt/',    'verb',      558, 5),
('demeanor',     'The way a person behaves and looks',                     'tavır',               '/dɪˈmiːnər/',     'noun',      559, 5),
('denounce',     'To criticize publicly and strongly',                     'kınamak',             '/dɪˈnaʊns/',      'verb',      560, 5),
('deplete',      'To greatly reduce the amount of something',              'tüketmek',            '/dɪˈpliːt/',      'verb',      561, 5),
('deplore',      'To strongly disapprove of something',                    'esef etmek',          '/dɪˈplɔːr/',      'verb',      562, 5),
('despondent',   'Very unhappy and without hope',                          'umutsuz',             '/dɪˈspɑːndənt/',  'adjective', 563, 5),
('digress',      'To move away from the main subject',                     'konudan sapmak',      '/daɪˈɡres/',      'verb',      564, 5),
('diligent',     'Working hard with care',                                 'çalışkan',            '/ˈdɪlɪdʒənt/',    'adjective', 565, 5),
('discern',      'To notice or understand with effort',                    'ayırt etmek',         '/dɪˈsɜːrn/',      'verb',      566, 5),
('disparage',    'To speak about someone without respect',                 'küçümsemek',          '/dɪˈspærɪdʒ/',    'verb',      567, 5),
('disparity',    'A great difference between things',                      'eşitsizlik',          '/dɪˈspærəti/',    'noun',      568, 5),
('disseminate',  'To spread information widely',                           'yaymak',              '/dɪˈsemɪneɪt/',   'verb',      569, 5),
('divulge',      'To reveal secret information',                           'ifşa etmek',          '/daɪˈvʌldʒ/',     'verb',      570, 5),
('eclectic',     'Coming from many different sources',                     'eklektik',            '/ɪˈklektɪk/',     'adjective', 571, 5),
('elucidate',    'To explain something clearly',                           'aydınlatmak',         '/ɪˈluːsɪdeɪt/',   'verb',      572, 5),
('emulate',      'To copy someone you admire',                             'örnek almak',         '/ˈemjəleɪt/',     'verb',      573, 5),
('enigmatic',    'Mysterious and difficult to understand',                 'esrarengiz',          '/ˌenɪɡˈmætɪk/',   'adjective', 574, 5),
('exacerbate',   'To make a problem worse',                                'şiddetlendirmek',     '/ɪɡˈzæsərbeɪt/',  'verb',      575, 5)
) AS v(word, definition, definition_tr, ipa, pos, freq, level)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE lower(w.word) = lower(v.word));

-- ============ C2 (level 6) ============
INSERT INTO words (word, definition, definition_tr, ipa, part_of_speech, frequency_rank, level_id)
SELECT v.word, v.definition, v.definition_tr, v.ipa, v.pos, v.freq, v.level
FROM (VALUES
('abrogate',      'To officially end a law or agreement',                   'feshetmek',           '/ˈæbrəɡeɪt/',      'verb',      601, 6),
('abstruse',      'Very difficult to understand',                           'anlaşılması güç',     '/əbˈstruːs/',      'adjective', 602, 6),
('acerbic',       'Sharp and critical in tone',                             'iğneleyici',          '/əˈsɜːrbɪk/',      'adjective', 603, 6),
('acrimony',      'Bitterness and anger in speech or debate',               'hınç',                '/ˈækrɪmoʊni/',     'noun',      604, 6),
('alacrity',      'Cheerful willingness and speed',                         'şevk',                '/əˈlækrəti/',      'noun',      605, 6),
('anachronistic', 'Belonging to a different time period',                   'çağdışı',             '/əˌnækrəˈnɪstɪk/', 'adjective', 606, 6),
('aplomb',        'Calm confidence in a difficult situation',               'soğukkanlılık',       '/əˈplɑːm/',        'noun',      607, 6),
('apocryphal',    'Well known but probably not true',                       'uydurma',             '/əˈpɑːkrɪfəl/',    'adjective', 608, 6),
('approbation',   'Official approval or praise',                            'takdir',              '/ˌæprəˈbeɪʃən/',   'noun',      609, 6),
('arcane',        'Known only by a few people',                             'gizemli',             '/ɑːrˈkeɪn/',       'adjective', 610, 6),
('ascetic',       'Living simply without pleasures',                        'münzevi',             '/əˈsetɪk/',        'adjective', 611, 6),
('assiduous',     'Showing great care and persistence',                     'gayretli',            '/əˈsɪdʒuəs/',      'adjective', 612, 6),
('avarice',       'Extreme greed for money',                                'açgözlülük',          '/ˈævərɪs/',        'noun',      613, 6),
('bellicose',     'Eager to fight or argue',                                'kavgacı',             '/ˈbelɪkoʊs/',      'adjective', 614, 6),
('bombastic',     'Using impressive but meaningless language',              'şatafatlı',           '/bɑːmˈbæstɪk/',    'adjective', 615, 6),
('bucolic',       'Relating to peaceful country life',                      'pastoral',            '/bjuːˈkɑːlɪk/',    'adjective', 616, 6),
('cacophony',     'A harsh mixture of unpleasant sounds',                   'kakofoni',            '/kəˈkɑːfəni/',     'noun',      617, 6),
('calumny',       'False statements made to damage a reputation',           'iftira',              '/ˈkæləmni/',       'noun',      618, 6),
('capitulate',    'To stop resisting and accept defeat',                    'teslim olmak',        '/kəˈpɪtʃəleɪt/',   'verb',      619, 6),
('circumspect',   'Careful to consider all risks before acting',            'ihtiyatlı',           '/ˈsɜːrkəmspekt/',  'adjective', 620, 6),
('clandestine',   'Done secretly, often illegally',                         'gizli kapaklı',       '/klænˈdestɪn/',    'adjective', 621, 6),
('cognizant',     'Fully aware of something',                               'bilincinde',          '/ˈkɑːɡnɪzənt/',    'adjective', 622, 6),
('conflagration', 'A large destructive fire',                               'büyük yangın',        '/ˌkɑːnfləˈɡreɪʃən/','noun',     623, 6),
('conundrum',     'A confusing and difficult problem',                      'muamma',              '/kəˈnʌndrəm/',     'noun',      624, 6),
('demagogue',     'A leader who appeals to emotions not reason',            'demagog',             '/ˈdeməɡɑːɡ/',      'noun',      625, 6),
('denigrate',     'To criticize unfairly and disrespectfully',              'karalamak',           '/ˈdenɪɡreɪt/',     'verb',      626, 6),
('desultory',     'Without a clear plan or purpose',                        'gelişigüzel',         '/ˈdesəltɔːri/',    'adjective', 627, 6),
('diaphanous',    'So thin and light you can see through it',               'şeffaf',              '/daɪˈæfənəs/',     'adjective', 628, 6),
('diatribe',      'A long angry speech of criticism',                       'sert eleştiri',       '/ˈdaɪətraɪb/',     'noun',      629, 6),
('dichotomy',     'A division into two opposite parts',                     'ikilik',              '/daɪˈkɑːtəmi/',    'noun',      630, 6),
('didactic',      'Intended to teach a moral lesson',                       'öğretici',            '/daɪˈdæktɪk/',     'adjective', 631, 6),
('dilettante',    'A person with only shallow interest in a subject',       'amatör heveskar',     '/ˈdɪlətɑːnt/',     'noun',      632, 6),
('duplicity',     'Dishonest behavior meant to deceive',                    'ikiyüzlülük',         '/duːˈplɪsəti/',    'noun',      633, 6),
('ebullient',     'Full of energy and enthusiasm',                          'coşkulu',             '/ɪˈbʊliənt/',      'adjective', 634, 6),
('efficacious',   'Producing the intended result',                          'etkili',              '/ˌefɪˈkeɪʃəs/',    'adjective', 635, 6),
('effrontery',    'Shockingly rude and bold behavior',                      'küstahlık',           '/ɪˈfrʌntəri/',     'noun',      636, 6),
('egregious',     'Shockingly bad',                                          'çok fena',            '/ɪˈɡriːdʒəs/',     'adjective', 637, 6),
('enervate',      'To make someone feel weak and tired',                    'takatsiz bırakmak',   '/ˈenərveɪt/',      'verb',      638, 6),
('ephemera',      'Things that are used or enjoyed briefly',                'geçici şeyler',       '/ɪˈfemərə/',       'noun',      639, 6),
('equanimity',    'Calmness in a difficult situation',                      'itidal',              '/ˌekwəˈnɪməti/',   'noun',      640, 6),
('equivocate',    'To speak vaguely to avoid the truth',                    'kaçamak konuşmak',    '/ɪˈkwɪvəkeɪt/',    'verb',      641, 6),
('erudite',       'Having great academic knowledge',                        'alim',                '/ˈerʊdaɪt/',       'adjective', 642, 6),
('evanescent',    'Quickly fading from sight or memory',                    'uçucu',               '/ˌevəˈnesənt/',    'adjective', 643, 6),
('exculpate',     'To show that someone is not guilty',                     'aklamak',             '/ˈekskəlpeɪt/',    'verb',      644, 6),
('execrable',     'Extremely bad or unpleasant',                            'berbat',              '/ˈeksɪkrəbəl/',    'adjective', 645, 6),
('exigent',       'Needing urgent attention',                               'acil',                '/ˈeksɪdʒənt/',     'adjective', 646, 6),
('expiate',       'To make up for doing something wrong',                   'kefaret ödemek',      '/ˈekspieɪt/',      'verb',      647, 6),
('extol',         'To praise highly',                                        'övmek',               '/ɪkˈstoʊl/',       'verb',      648, 6),
('fatuous',       'Silly and without thought',                              'ahmakça',             '/ˈfætʃuəs/',       'adjective', 649, 6),
('fecund',        'Very productive or fertile',                             'verimli',             '/ˈfekənd/',        'adjective', 650, 6),
('garrulous',     'Talking too much about unimportant things',              'geveze',              '/ˈɡærələs/',       'adjective', 651, 6),
('grandiloquent', 'Using fancy language to impress',                        'tumturaklı',          '/ɡrænˈdɪləkwənt/', 'adjective', 652, 6),
('gregarious',    'Enjoying the company of others',                         'sosyal',              '/ɡrɪˈɡeriəs/',     'adjective', 653, 6),
('hegemony',      'Dominance of one group over others',                     'hegemonya',           '/hɪˈdʒeməni/',     'noun',      654, 6),
('iconoclast',    'A person who attacks accepted beliefs',                  'gelenek yıkıcı',      '/aɪˈkɑːnəklæst/',  'noun',      655, 6),
('idiosyncrasy',  'An unusual habit unique to a person',                    'kendine özgülük',     '/ˌɪdiəˈsɪŋkrəsi/', 'noun',      656, 6),
('impecunious',   'Having little or no money',                              'meteliksiz',          '/ˌɪmpɪˈkjuːniəs/', 'adjective', 657, 6),
('imperturbable', 'Impossible to upset or excite',                          'sarsılmaz',           '/ˌɪmpərˈtɜːrbəbəl/','adjective',658, 6),
('impetuous',     'Acting quickly without thinking',                        'düşüncesiz',          '/ɪmˈpetʃuəs/',     'adjective', 659, 6),
('inchoate',      'Just begun and not fully formed',                        'başlangıç halinde',   '/ɪnˈkoʊət/',       'adjective', 660, 6),
('indefatigable', 'Never getting tired',                                    'yorulmak bilmez',     '/ˌɪndɪˈfætɪɡəbəl/','adjective', 661, 6),
('ineffable',     'Too great to be described in words',                     'tarifsiz',            '/ɪnˈefəbəl/',      'adjective', 662, 6),
('inimical',      'Harmful or unfriendly',                                  'zararlı',             '/ɪˈnɪmɪkəl/',      'adjective', 663, 6),
('insidious',     'Spreading harm in a hidden gradual way',                 'sinsi',               '/ɪnˈsɪdiəs/',      'adjective', 664, 6),
('intransigent',  'Refusing to change opinions or behavior',                'uzlaşmaz',            '/ɪnˈtrænsɪdʒənt/', 'adjective', 665, 6),
('inveterate',    'Having a long established habit',                        'müzmin',              '/ɪnˈvetərət/',     'adjective', 666, 6),
('lassitude',     'Lack of energy and enthusiasm',                          'bitkinlik',           '/ˈlæsɪtuːd/',      'noun',      667, 6),
('mellifluous',   'Sounding sweet and smooth',                              'tatlı sesli',         '/məˈlɪfluəs/',     'adjective', 668, 6),
('mendacious',    'Not telling the truth',                                  'yalancı',             '/menˈdeɪʃəs/',     'adjective', 669, 6),
('obdurate',      'Stubbornly refusing to change',                          'inatçı',              '/ˈɑːbdʊrət/',      'adjective', 670, 6),
('perspicacious', 'Quick to notice and understand things',                  'keskin görüşlü',      '/ˌpɜːrspɪˈkeɪʃəs/','adjective', 671, 6),
('quixotic',      'Idealistic but not practical',                           'hayalperest',         '/kwɪkˈsɑːtɪk/',    'adjective', 672, 6),
('sagacious',     'Wise and showing good judgment',                         'bilge',               '/səˈɡeɪʃəs/',      'adjective', 673, 6),
('taciturn',      'Saying very little',                                      'suskun',              '/ˈtæsɪtɜːrn/',     'adjective', 674, 6),
('vacillate',     'To keep changing between opinions',                      'bocalamak',           '/ˈvæsəleɪt/',      'verb',      675, 6)
) AS v(word, definition, definition_tr, ipa, pos, freq, level)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE lower(w.word) = lower(v.word));

-- ============ Ek 60 kelime (seviye başına 10) ============
INSERT INTO words (word, definition, definition_tr, ipa, part_of_speech, frequency_rank, level_id)
SELECT v.word, v.definition, v.definition_tr, v.ipa, v.pos, v.freq, v.level
FROM (VALUES
-- A1
('fish',        'An animal that lives and swims in water',              'balık',            '/fɪʃ/',           'noun',      176, 1),
('bird',        'An animal with wings and feathers that can fly',       'kuş',              '/bɜːrd/',         'noun',      177, 1),
('egg',         'A round food that comes from chickens',                'yumurta',          '/eɡ/',            'noun',      178, 1),
('rice',        'Small white grains cooked as food',                    'pirinç',           '/raɪs/',          'noun',      179, 1),
('sugar',       'A sweet substance used in food and drinks',            'şeker',            '/ˈʃʊɡər/',        'noun',      180, 1),
('salt',        'A white substance used to flavor food',                'tuz',              '/sɔːlt/',         'noun',      181, 1),
('fruit',       'Sweet food that grows on trees and plants',            'meyve',            '/fruːt/',         'noun',      182, 1),
('garden',      'An area next to a house with plants',                  'bahçe',            '/ˈɡɑːrdən/',      'noun',      183, 1),
('mother',      'A female parent',                                      'anne',             '/ˈmʌðər/',        'noun',      184, 1),
('father',      'A male parent',                                        'baba',             '/ˈfɑːðər/',       'noun',      185, 1),
-- A2
('breakfast',   'The first meal of the day',                            'kahvaltı',         '/ˈbrekfəst/',     'noun',      276, 2),
('dinner',      'The main meal eaten in the evening',                   'akşam yemeği',     '/ˈdɪnər/',        'noun',      277, 2),
('kitchen',     'The room where food is cooked',                        'mutfak',           '/ˈkɪtʃɪn/',       'noun',      278, 2),
('clothes',     'Things you wear on your body',                         'kıyafet',          '/kloʊðz/',        'noun',      279, 2),
('shoes',       'Things you wear on your feet',                         'ayakkabı',         '/ʃuːz/',          'noun',      280, 2),
('umbrella',    'A thing you hold over your head in the rain',          'şemsiye',          '/ʌmˈbrelə/',      'noun',      281, 2),
('bridge',      'A structure built over a river or road',               'köprü',            '/brɪdʒ/',         'noun',      282, 2),
('island',      'Land surrounded by water',                             'ada',              '/ˈaɪlənd/',       'noun',      283, 2),
('mountain',    'A very high hill',                                     'dağ',              '/ˈmaʊntən/',      'noun',      284, 2),
('river',       'A long line of water that flows to the sea',           'nehir',            '/ˈrɪvər/',        'noun',      285, 2),
-- B1
('purpose',     'The reason for doing something',                       'amaç',             '/ˈpɜːrpəs/',      'noun',      376, 3),
('realize',     'To suddenly understand something',                     'fark etmek',       '/ˈriːəlaɪz/',     'verb',      377, 3),
('recommend',   'To say that something is good and worth trying',       'tavsiye etmek',    '/ˌrekəˈmend/',    'verb',      378, 3),
('reduce',      'To make something smaller in amount',                  'azaltmak',         '/rɪˈduːs/',       'verb',      379, 3),
('refuse',      'To say no to something',                               'reddetmek',        '/rɪˈfjuːz/',      'verb',      380, 3),
('regret',      'To feel sorry about something you did',                'pişman olmak',     '/rɪˈɡret/',       'verb',      381, 3),
('relationship','The way people are connected to each other',           'ilişki',           '/rɪˈleɪʃənʃɪp/',  'noun',      382, 3),
('responsible', 'Having the duty to take care of something',            'sorumlu',          '/rɪˈspɑːnsəbəl/', 'adjective', 383, 3),
('satisfy',     'To make someone pleased by giving what they want',     'tatmin etmek',     '/ˈsætɪsfaɪ/',     'verb',      384, 3),
('solution',    'A way of solving a problem',                           'çözüm',            '/səˈluːʃən/',     'noun',      385, 3),
-- B2
('facilitate',  'To make a process easier',                             'kolaylaştırmak',   '/fəˈsɪlɪteɪt/',   'verb',      476, 4),
('feasible',    'Possible to do or achieve',                            'yapılabilir',      '/ˈfiːzəbəl/',     'adjective', 477, 4),
('fluctuate',   'To change frequently between levels',                  'dalgalanmak',      '/ˈflʌktʃueɪt/',   'verb',      478, 4),
('fragile',     'Easily broken or damaged',                             'kırılgan',         '/ˈfrædʒəl/',      'adjective', 479, 4),
('hinder',      'To make progress difficult',                           'engellemek',       '/ˈhɪndər/',       'verb',      480, 4),
('impose',      'To force a rule or duty on people',                    'dayatmak',         '/ɪmˈpoʊz/',       'verb',      481, 4),
('incentive',   'Something that encourages you to act',                 'teşvik',           '/ɪnˈsentɪv/',     'noun',      482, 4),
('integrate',   'To combine parts into a whole',                        'bütünleştirmek',   '/ˈɪntɪɡreɪt/',    'verb',      483, 4),
('justify',     'To show that something is right or reasonable',        'gerekçelendirmek', '/ˈdʒʌstɪfaɪ/',    'verb',      484, 4),
('legitimate',  'Allowed by law or done fairly',                        'meşru',            '/lɪˈdʒɪtɪmət/',   'adjective', 485, 4),
-- C1
('exemplify',   'To be a typical example of something',                 'örnek teşkil etmek','/ɪɡˈzemplɪfaɪ/', 'verb',      576, 5),
('explicit',    'Stated clearly and directly',                          'açık',             '/ɪkˈsplɪsɪt/',    'adjective', 577, 5),
('feign',       'To pretend to feel something',                         'numara yapmak',    '/feɪn/',          'verb',      578, 5),
('frugal',      'Careful not to spend much money',                      'tutumlu',          '/ˈfruːɡəl/',      'adjective', 579, 5),
('futile',      'Having no chance of success',                          'boşuna',           '/ˈfjuːtəl/',      'adjective', 580, 5),
('hamper',      'To slow down progress',                                'sekteye uğratmak', '/ˈhæmpər/',       'verb',      581, 5),
('impartial',   'Treating all sides equally',                           'tarafsız',         '/ɪmˈpɑːrʃəl/',    'adjective', 582, 5),
('impede',      'To delay or block progress',                           'engellemek',       '/ɪmˈpiːd/',       'verb',      583, 5),
('incessant',   'Continuing without stopping',                          'aralıksız',        '/ɪnˈsesənt/',     'adjective', 584, 5),
('indifferent', 'Having no interest or concern',                        'kayıtsız',         '/ɪnˈdɪfrənt/',    'adjective', 585, 5),
-- C2
('venerate',    'To respect someone deeply',                            'yüceltmek',        '/ˈvenəreɪt/',     'verb',      676, 6),
('verbose',     'Using more words than necessary',                      'laf kalabalığı yapan','/vərˈboʊs/',   'adjective', 677, 6),
('vicissitude', 'An unexpected change in life or fortune',              'iniş çıkış',       '/vɪˈsɪsɪtuːd/',   'noun',      678, 6),
('sycophant',   'A person who flatters powerful people for gain',       'dalkavuk',         '/ˈsɪkəfænt/',     'noun',      679, 6),
('soporific',   'Making you feel sleepy',                               'uyutucu',          '/ˌsɑːpəˈrɪfɪk/',  'adjective', 680, 6),
('sardonic',    'Mocking in a bitter way',                              'alaycı',           '/sɑːrˈdɑːnɪk/',   'adjective', 681, 6),
('sanguine',    'Hopeful and positive in a bad situation',              'iyimser',          '/ˈsæŋɡwɪn/',      'adjective', 682, 6),
('recalcitrant','Refusing to obey rules or authority',                  'dik başlı',        '/rɪˈkælsɪtrənt/', 'adjective', 683, 6),
('pellucid',    'Very clear and easy to understand',                    'berrak',           '/pəˈluːsɪd/',     'adjective', 684, 6),
('obsequious',  'Too eager to please or obey',                          'yaltakçı',         '/əbˈsiːkwiəs/',   'adjective', 685, 6)
) AS v(word, definition, definition_tr, ipa, pos, freq, level)
WHERE NOT EXISTS (SELECT 1 FROM words w WHERE lower(w.word) = lower(v.word));
